#!/usr/bin/env bash
#!/usr/bin/env bash
# Change permissions for /etc/nginx recursively
sudo chmod -R 755 /etc/nginx/
sudo systemctl stop apache2
sudo sed -i 's/8080/8081/g' /etc/apache2/ports.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
