#!/usr/bin/env bash
# Bash script to install and configure Nginx web server

# Update package lists and upgrade existing packages
sudo apt-get update && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Modify Nginx default configuration to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo service nginx restart

# Check if Nginx is running and accessible on port 80
if curl -s -o /dev/null -w "%{http_code}" localhost == "200"; then
    echo "Nginx is installed on your web01 server and accepting traffic on port 80."
else
    echo "Nginx configuration failed or is not accepting traffic on port 80."
fi

# Check if Nginx returns a page containing "Holberton School" at its root
if curl -s localhost | grep -q "Holberton School"; then
    echo "Nginx returns at its root / a page that contains Holberton School."
else
    echo "Nginx does not return a page containing Holberton School at its root."
fi
