#!/usr/bin/env bash
# Installing Nginx on Ubuntu
# Nginx is listening on port 80
# The GET request should return a page containing "Holberton School"

# Update package lists and upgrade existing packages
sudo apt-get update && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Create a directory called html inside your nginx server
sudo mkdir -p /var/www/html

# Create a file inside that directory called index.html
sudo touch /var/www/html/index.html

# Display your message then
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx service
sudo service nginx restart

# Check if Nginx is running and accessible on port 80
sleep 2 # Wait for Nginx to restart
if curl -s localhost | grep -q "Holberton School"; then
    echo "Nginx installed and configured successfully."
else
    echo "Nginx configuration failed. Please check logs for more information."
fi

# Check if Nginx returns 200 when querying /
if curl -s -o /dev/null -w "%{http_code}" localhost == "200"; then
    echo "Nginx returns 200 when querying /."
else
    echo "Nginx does not return 200 when querying /."
fi
