#!/usr/bin/env bash
#Installing Nginx on Ubuntu
#Nginx is listening on port 80
#The GET request should return a page containing "Holberton School"

# Update and upgrade the package lists
sudo apt-get update && sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Create a directory called html inside your nginx server
sudo mkdir -p /var/www/html

# Create a file inside that directory called index.html
echo "Holberton School" | sudo tee /var/www/html/index.html

# Restart Nginx service
sudo service nginx restart

# Check if Nginx is running
nginx_status=$(sudo service nginx status)
if [[ $nginx_status == *"active (running)"* ]]; then
    echo "Nginx is installed on your web01 server and accepting traffic on port 80"
else
    echo "Nginx failed to start."
    exit 1
fi

# Check if Nginx returns a page containing "Holberton School"
curl_output=$(curl -s http://localhost)
if [[ $curl_output == *"Holberton School"* ]]; then
    echo "Nginx returns at its root / a page that contains Holberton School"
else
    echo "Nginx does not return a page containing Holberton School."
    exit 1
fi
